server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zones
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
